### ISSUE TITLE
Ability to return previous URL even when currently no previous items

### ISSUE THREAD

**Issue by trevorgehman** [amrnn90/laravel-cursor-paginator#11]
So right now I'm using this package to return a collection of inbox threads sorted by `created_at,id`. On the first page of results, the `$meta['previous']` value is `null`, because it's the first page. 

The issue is that let's say some time has passed and I receive a notification that new threads are available. I'd like to simply pull in new threads, which means I'd need to know the value for the `previous_page` cursor.

So I'm wondering whether we could have the ability to return the `previous_page` cursor even when on the first page, and rely on a boolean `has_previous` or something to know whether to use it?

**Comment by amrnn90** [comment]
Sorry for the late response @trevorgehman 
Added what you asked for in v2.0.0
