### ISSUE TITLE
Allow base64 encoded cursor?

### ISSUE THREAD

**Issue by trevorgehman** [amrnn90/laravel-cursor-paginator#4]
It seems to be a common approach to base64 encode the cursor. I've seen Slack do it (https://slack.engineering/evolving-api-pagination-at-slack-1c1f644f8e12) as well as Facebook (https://developers.facebook.com/docs/graph-api/using-graph-api/). 

What do you think about this? I like the idea of the cursor being an opaque string. One downside to the base64 encoding is the possibly present trailing equal signs `=` need to be url encoded. We could, of course, just strip those since they're only padding.

EDIT: Sorry to be adding multiple issues. I really appreciate your work on this package & want to provide useful feedback.

**Comment by amrnn90** [comment]
That's a good idea, I'll try implementing it as soon as I can...feel free to submit a PR  if you want to.
No worries about the multiple issues, that's what they're made for...Your valuable feedback is much appreciated.

**Comment by amrnn90** [comment]
Added by #5
